# Generated by Django 5.1 on 2026-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='teacher', help_text='Учитель или ученик: у них разные интерфейсы целиком.', max_length=8, verbose_name='kind'),
        ),
    ]
