# Generated by Django 5.1 on 2026-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="forward_feedback",
            field=models.BooleanField(
                default=False,
                help_text="Superusers only: send every new feedback message to this account's address.",
                verbose_name="forward feedback by email",
            ),
        ),
    ]
