"""
Третий вид пользователя: родитель.

Не разновидность ученика, а свой вид. Видит он то же, что ребёнок, но детей у
него несколько, разговор с учителем свой, а оповещения расходятся в обе
стороны — сложить это в ученика значило бы показывать каждому чужое.

Данные не трогаются: у существующих учёток вид остаётся прежним, меняется
только список допустимых значений.
"""

# Generated by Django 5.1 on 2026-08-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_forward_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="kind",
            field=models.CharField(
                choices=[
                    ("teacher", "teacher"),
                    ("student", "student"),
                    ("parent", "parent"),
                ],
                default="teacher",
                help_text="Учитель или ученик: у них разные интерфейсы целиком.",
                max_length=8,
                verbose_name="kind",
            ),
        ),
    ]
