"""
Внешний номер человека — Student ID из выгрузки ManageBac.

Ключ сопоставления для импорта, а не данные о человеке: без него ученик, которому
в источнике сменили почту, приехал бы вторым человеком. Уникален в пределах
школы, и только когда заполнен: пустота — обычное состояние всех, кого не
привозили.
"""

# Generated by Django 5.1 on 2026-09-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_kind"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("schools", "0012_family_invitation_grants_no_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Student ID in the source system (ManageBac). Filled by imports only.",
                max_length=64,
                verbose_name="external id",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", ""), ("school__isnull", False)),
                fields=("school", "external_id"),
                name="one_external_id_per_school",
            ),
        ),
    ]
