"""
Код из письма — вторая дверь для тех, у кого нет Google-аккаунта.

Хранится хэш кода, срок, число попыток и отметка использования. Данных в
таблице нет, пока дверью не воспользовались.
"""

# Generated by Django 5.1 on 2026-09-07 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(max_length=64, verbose_name="code hash"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="attempts"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="used at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "login code",
                "verbose_name_plural": "login codes",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
