"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path

import environ
from botocore.config import Config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

SECRET_KEY = env("SECRET_KEY", default="dev-insecure-key-change-me")
DEBUG = env("DEBUG")

# A door for browser tests: a token by email, and a database reset. Never on
# in production — see accounts/e2e.py for why it is closed three times over.
E2E_TEST_LOGIN = env.bool("E2E_TEST_LOGIN", default=False)

# Кого этот контур пускает внутрь. Пусто — всех, кого пустил Google: так
# живёт прод, где допуск даёт приглашение школы. Список адресов закрывает
# контур, у которого своей публики нет, — стенд. Разбор в accounts/door.py.
LOGIN_ALLOWED_EMAILS = env.list("LOGIN_ALLOWED_EMAILS", default=[])
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',

    'accounts',
    'schools',
    'calendars',
    'schedule',
    'plans',
    'library',
    'files',
    'works',
    'onboarding',
    'vision',
    'bank',
    'feedback',
    'families',
    'talks',
    'bookmarks',
]

AUTH_USER_MODEL = "accounts.User"

SITE_ID = 1

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB", default="lessons"),
        "USER": env("POSTGRES_USER", default="lessons"),
        "PASSWORD": env("POSTGRES_PASSWORD", default="lessons"),
        "HOST": env("POSTGRES_HOST", default="db"),
        "PORT": env.int("POSTGRES_PORT", default=5432),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = BASE_DIR / "staticfiles"


# Файлы пользователей: Cloudflare R2
#
# В R2 едут только вложения к урокам. Статика Django остаётся на диске и
# раздаётся nginx — она пересобирается на каждой выкатке, класть её в
# объектное хранилище незачем.

# Ключи объектов строит files/storage.py; здесь только подключение.
R2_BUCKET_NAME = env("R2_BUCKET_NAME", default="")
R2_ENDPOINT_URL = env("R2_ENDPOINT_URL", default="")

# Клиент собирается здесь целиком, а не по частям: если передать
# client_config, django-storages перестаёт читать signature_version и
# addressing_style из настроек — они должны лежать внутри Config.
R2_CLIENT_CONFIG = Config(
    # R2 понимает только virtual-hosted style и подпись v4
    s3={"addressing_style": "virtual"},
    signature_version="s3v4",
    # хранилище лежит за сетью: без таймаутов недоступный R2 подвесил бы
    # воркер gunicorn, а не вернул ошибку
    connect_timeout=5,
    read_timeout=20,
    retries={"max_attempts": 2, "mode": "standard"},
)

# Резервный бакет: копия вложений, которую делает scripts/backup-files.sh.
# Приложение в него не пишет и не читает — он подключается только командой
# backup_files, поэтому и ключи здесь отдельные: у токена приложения прав на
# резерв нет вовсе, а токен резерва видит оба бакета.
R2_BACKUP_BUCKET_NAME = env("R2_BACKUP_BUCKET_NAME", default="")
R2_BACKUP_ACCESS_KEY_ID = env("R2_BACKUP_ACCESS_KEY_ID", default="")
R2_BACKUP_SECRET_ACCESS_KEY = env("R2_BACKUP_SECRET_ACCESS_KEY", default="")

# сколько живёт ссылка на скачивание
FILE_URL_TTL = env.int("FILE_URL_TTL", default=300)
# 20 МБ на файл; nginx пропускает 25m, запас на оболочку multipart
# Ключ Anthropic: им читаются шапки отсканированных бланков. Нет ключа —
# чтение честно отказывается (`ai_key_missing`), остальное приложение работает.
ANTHROPIC_API_KEY = env("ANTHROPIC_API_KEY", default="")

# Какой моделью читать шапку скана. Умолчание дешёвое: полоска — это имя и
# шестнадцать цифр в отдельных квадратиках, и на цифрах разницы между моделями
# нет. Разница есть на **рукописном имени**, и там она стоит втрое дороже,
# поэтому выбор оставлен переменной: попробовать на одной пачке и сравнить
# глазами — работа на одну строку в .env, а не на правку кода.
# Модель, которой нет в vision/prices.py, к вызову не допускается вовсе.
SCAN_HEADER_MODEL = env("SCAN_HEADER_MODEL", default="claude-haiku-4-5-20251001")

# Второй читатель той же полоски — Mathpix, распознаватель рукописного. Он не
# заменяет модель и не может: он не знает ни списка класса, ни того, что сумма
# не задача. Он нужен ради **расхождения**: модель ошибается молча, и поймать
# такую ошибку можно только свидетельством того, кто ошибается иначе.
# Ключей нет — второго читателя нет, и пачка разбирается ровно как раньше.
MATHPIX_APP_ID = env("MATHPIX_APP_ID", default="")
MATHPIX_APP_KEY = env("MATHPIX_APP_KEY", default="")

# Ещё один распознаватель, Yandex Vision OCR. Заведён ради контура, до
# Anthropic не достающего: там языковой модели нет вовсе, а читать надо. Он
# тоже не заменяет модель — списка класса не знает, — но ошибается иначе и
# Mathpix, и модели, а два свидетеля разной природы стоят больше двух
# одинаковых. Ключа нет — читателя нет.
YANDEX_OCR_API_KEY = env("YANDEX_OCR_API_KEY", default="")
# Нужен, только если ключ выдан не сервисному аккаунту: с API-ключом сервис
# сам берёт каталог, где аккаунт заведён.
YANDEX_FOLDER_ID = env("YANDEX_FOLDER_ID", default="")

FILE_MAX_BYTES = env.int("FILE_MAX_BYTES", default=20 * 1024 * 1024)
# квота школы: сумма размеров её уникальных файлов
SCHOOL_FILE_QUOTA_BYTES = env.int(
    "SCHOOL_FILE_QUOTA_BYTES", default=5 * 1024 * 1024 * 1024
)

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    },
    # именованное хранилище: обращаться к нему нужно явно, случайно положить
    # что-то в R2 через FileField нельзя
    "files": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": R2_BUCKET_NAME,
            "endpoint_url": R2_ENDPOINT_URL,
            "access_key": env("R2_ACCESS_KEY_ID", default=""),
            "secret_key": env("R2_SECRET_ACCESS_KEY", default=""),
            "region_name": "auto",
            "client_config": R2_CLIENT_CONFIG,
            # R2 не поддерживает ACL: любой параметр вроде default_acl
            # приводит к ошибке подписи, поэтому его здесь и нет
            "querystring_auth": True,
            "querystring_expire": FILE_URL_TTL,
            # в ключе есть uuid, так что столкнуться два объекта не могут;
            # без этого флага django-storages делал бы лишний HEAD перед
            # каждой загрузкой, чтобы подобрать свободное имя
            "file_overwrite": True,
        },
    },
}


# Аутентификация

AUTHENTICATION_BACKENDS = [
    # логин по паролю в /admin/
    "django.contrib.auth.backends.ModelBackend",
    # вход через социальные провайдеры
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Свой раннер ровно ради одного: под тестами хранилище файлов подменяется
# на память, и ни один тест не может случайно постучаться в R2.
TEST_RUNNER = "config.testing.Runner"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

REST_AUTH = {
    "USE_JWT": False,
    "TOKEN_MODEL": "rest_framework.authtoken.models.Token",
    # SPA работает по токену, сессия Django для API не нужна
    "SESSION_LOGIN": False,
}

# --- почта -------------------------------------------------------------------
#
# Нужна ровно для одного: пересылать суперпользователю обращения из
# приложения (`feedback`). Ни писем пользователям, ни подтверждения адреса
# тут нет — вход идёт через Google, и адрес подтверждает он.
#
# Без `EMAIL_HOST` письма печатаются в лог контейнера, и это **рабочее
# состояние**, а не заглушка: обращения всё равно лежат в базе и видны на
# своей странице, письмо — только уведомление. Молчащий SMTP на localhost
# был бы хуже: он глотает письма, ничего не сообщая.
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
# Таймаут — не тонкая настройка, а условие того, что письмо остаётся
# уведомлением. Без него `smtplib` ждёт соединения **бесконечно**, и
# `fail_silently` тут не помогает: он ловит исключение, а зависание — это
# отсутствие исключения. Наружу это вышло пятисоткой на отправке обращения:
# хостер стенда режет исходящий SMTP, соединение не отбивается, а висит, и
# gunicorn убивает воркер по своему таймауту. То есть ровно то, что
# `fail_silently` был призван исключить, — сообщение записано, а человеку
# сказано «не получилось».
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=10)
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER or "lesson-tracker@localhost"
)

# allauth: пользователь опознаётся по email, username в модели нет
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*"]
# email уже подтверждён Google, свой цикл подтверждения не нужен
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = "accounts.adapter.SocialAccountAdapter"

# Вход через Google подхватывает уже существующий локальный аккаунт с тем же
# email. allauth применяет это только к адресам, которые провайдер отдал как
# подтверждённые (у Google — claim email_verified), см. adapter.authenticate_by_email.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
# Привязать SocialAccount к найденному пользователю, иначе связь не сохранится
# и при смене email в Google вход перестанет работать.
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        # ключи берём из окружения, SocialApp в админке не заводим
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID", default=""),
            "secret": env("GOOGLE_CLIENT_SECRET", default=""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=["http://localhost:5173", "http://127.0.0.1:5173"],
)


# Работа за nginx

# формы админки шлют POST на тот же origin, откуда открыта страница
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# nginx терминирует TLS и передаёт исходную схему заголовком
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# включается после того, как на сервере поднят HTTPS
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
# 0 = HSTS выключен; включать только когда HTTPS уже работает стабильно
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)