# Generated by Django 5.1 on 2026-08-12 13:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.school', verbose_name='school')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='calendars.schoolyear', verbose_name='school year')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LessonSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('lesson_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='lesson number')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='cancelled')),
                ('is_extra', models.BooleanField(default=False, verbose_name='extra lesson')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='schedule.course', verbose_name='course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='calendars.schoolyear', verbose_name='school year')),
            ],
            options={
                'verbose_name': 'lesson slot',
                'verbose_name_plural': 'lesson slots',
                'ordering': ('date', 'lesson_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('school', 'year', 'name'), name='unique_course_name_per_year'),
        ),
        migrations.AddIndex(
            model_name='lessonslot',
            index=models.Index(fields=['teacher', 'date'], name='slot_teacher_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonslot',
            index=models.Index(fields=['course', 'date'], name='slot_course_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonslot',
            constraint=models.UniqueConstraint(fields=('teacher', 'course', 'date', 'lesson_number'), name='unique_slot_per_teacher_course_day'),
        ),
        migrations.AddConstraint(
            model_name='lessonslot',
            constraint=models.CheckConstraint(condition=models.Q(('lesson_number__gte', 1), ('lesson_number__lte', 10)), name='lesson_number_in_range'),
        ),
    ]
