# Generated by Django 5.1 on 2026-08-12 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('schedule', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('lesson_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='lesson number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_slots', to='schedule.course', verbose_name='course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_slots', to='schools.school', verbose_name='school')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_slots', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_slots', to='calendars.schoolyear', verbose_name='school year')),
            ],
            options={
                'verbose_name': 'school timetable lesson',
                'verbose_name_plural': 'school timetable',
                'ordering': ('date', 'lesson_number'),
                'indexes': [models.Index(fields=['school', 'year', 'teacher', 'date'], name='master_teacher_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'date', 'lesson_number'), name='unique_master_slot_per_course_day'), models.CheckConstraint(condition=models.Q(('lesson_number__gte', 1), ('lesson_number__lte', 10)), name='master_lesson_number_in_range')],
            },
        ),
    ]
