# Generated by Django 5.1 on 2026-08-11 21:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('lesson_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='номер урока')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='отменён')),
                ('is_extra', models.BooleanField(default=False, verbose_name='сверх расписания')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedule.schoolclass', verbose_name='класс')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='calendars.schoolyear', verbose_name='учебный год')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
                'ordering': ('date', 'lesson_number'),
                'indexes': [models.Index(fields=['school_class', 'date'], name='slot_class_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_class', 'date', 'lesson_number'), name='unique_slot_per_class_day'), models.CheckConstraint(condition=models.Q(('lesson_number__gte', 1), ('lesson_number__lte', 10)), name='lesson_number_in_range')],
            },
        ),
    ]
