# Generated by Django 5.1 on 2026-08-12 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_term'),
        ('schedule', '0002_lessonslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonslot',
            options={'ordering': ('date', 'lesson_number'), 'verbose_name': 'lesson slot', 'verbose_name_plural': 'lesson slots'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ('name',), 'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterField(
            model_name='lessonslot',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='lessonslot',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='cancelled'),
        ),
        migrations.AlterField(
            model_name='lessonslot',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='extra lesson'),
        ),
        migrations.AlterField(
            model_name='lessonslot',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='lesson number'),
        ),
        migrations.AlterField(
            model_name='lessonslot',
            name='reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='lessonslot',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedule.schoolclass', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='lessonslot',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='calendars.schoolyear', verbose_name='school year'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='calendars.schoolyear', verbose_name='school year'),
        ),
    ]
