# Generated by Django 5.1 on 2026-08-13 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_grade_levels_and_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='level',
            field=models.PositiveSmallIntegerField(help_text='The year of study counted from the first one, not the number inside the name. «MYP 4» is the ninth year of study, so its level is 9 — that is what keeps sorting right in a school that uses both systems.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='year of study'),
        ),
    ]
