# Generated by Django 5.1 on 2026-08-13 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_course_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMethodist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methodists_assigned', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodists', to='schedule.course', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodist_of', to=settings.AUTH_USER_MODEL, verbose_name='methodist')),
            ],
            options={
                'verbose_name': 'course methodist',
                'verbose_name_plural': 'course methodists',
                'ordering': ('course__name', 'user__last_name'),
                'constraints': [models.UniqueConstraint(fields=('course', 'user'), name='one_methodist_row_per_course')],
            },
        ),
    ]
