# Generated by Django 5.1 on 2026-08-14 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_coursemethodist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, help_text='Снят с курса: работать нельзя, своё прошлое видно.', null=True, verbose_name='removed at')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_enrolled', to=settings.AUTH_USER_MODEL, verbose_name='enrolled by')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schedule.course', verbose_name='course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'course student',
                'verbose_name_plural': 'course students',
                'ordering': ('course__name', 'student__last_name', 'student__email'),
                'indexes': [models.Index(fields=['student', 'removed_at'], name='active_enrolment_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'student'), name='one_enrolment_row_per_course')],
            },
        ),
    ]
