# Generated by Django 5.1 on 2026-08-14 19:55

from django.conf import settings
from django.db import migrations, models


def keep_the_first_teacher(apps, schema_editor):
    """
    Ведущий у курса один; если назначенных несколько, остаётся первый.

    Снятие назначения ничего не удаляет — это записано в самой модели, — так
    что уроки и работы «лишних» остаются при них. Первый, а не последний,
    потому что первым назначают того, кто курс и ведёт; заменивший его
    приходит вторым.
    """
    CourseAssignment = apps.get_model("schedule", "CourseAssignment")

    seen = set()
    for row in CourseAssignment.objects.order_by("course_id", "created_at", "id"):
        if row.course_id in seen:
            print(f"  снято лишнее назначение с курса {row.course_id}")
            row.delete()
        else:
            seen.add(row.course_id)


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_coursestudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(keep_the_first_teacher, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='courseassignment',
            name='unique_course_assignment',
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(fields=('course',), name='one_teacher_per_course'),
        ),
    ]
