# Generated by Django 5.1 on 2026-08-15 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('schedule', '0012_rename_lessonslot_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='schedule.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='calendars.schoolyear', verbose_name='school year'),
        ),
    ]
