# Generated by Django 5.1 on 2026-08-15 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_remove_planbaseline_baseline_owner_status_idx_and_more'),
        ('schedule', '0013_alter_lesson_course_alter_lesson_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('date', 'lesson_number'), 'verbose_name': 'lesson', 'verbose_name_plural': 'lessons'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='covered',
            field=models.ForeignKey(blank=True, help_text='Строка плана, которую разобрали на этом уроке.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_at', to='plans.plannode', verbose_name='what was covered'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='taught_by',
            field=models.ForeignKey(blank=True, help_text='Заполняется только для замены: обычно урок ведёт ведущий курса.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_taught', to=settings.AUTH_USER_MODEL, verbose_name='taught by'),
        ),
    ]
