# Generated by Django 5.1 on 2026-08-15 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_rename_lesson_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'was there'), ('absent', 'was not'), ('late', 'came late')], max_length=8, verbose_name='status')),
                ('note', models.CharField(blank=True, help_text='Причина словами: список причин у каждой школы свой.', max_length=200, verbose_name='note')),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL, verbose_name='marked by')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='schedule.slot', verbose_name='lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'attendance mark',
                'verbose_name_plural': 'attendance',
                'ordering': ('student__last_name', 'student__email'),
                'constraints': [models.UniqueConstraint(fields=('slot', 'student'), name='one_attendance_row_per_lesson')],
            },
        ),
    ]
