"""
Расписание звонков: во сколько начинается и кончается урок с этим номером.

Справочник школы, рядом с предметами и параллелями. Номер урока остаётся
ключом занятия — время живёт здесь и подставляется на показ, иначе перенос
звонка на десять минут переписывал бы десять тысяч строк расписания.

Ограничение `a_lesson_ends_after_it_starts` не про показ: по длительности
считают, успевает ли класс перейти между кабинетами, и отрицательная перемена
читается как ошибка данных где-то ещё.
"""

# Generated by Django 5.1 on 2026-08-23 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0016_attendance"),
        ("schools", "0010_alter_invitation_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="BellTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="lesson number",
                    ),
                ),
                ("starts_at", models.TimeField(verbose_name="starts at")),
                ("ends_at", models.TimeField(verbose_name="ends at")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bells",
                        to="schools.school",
                        verbose_name="school",
                    ),
                ),
            ],
            options={
                "verbose_name": "bell time",
                "verbose_name_plural": "bell times",
                "ordering": ("number",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "number"), name="one_bell_per_lesson_number"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="a_lesson_ends_after_it_starts",
                    ),
                ],
            },
        ),
    ]
