# Generated by Django 5.1 on 2026-08-24 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0017_belltime"),
        ("schools", "0010_alter_invitation_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Несколько занятий разом — норма: спортзал, актовый зал. О совпадениях в таком кабинете не предупреждаем.",
                        verbose_name="shared",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Из выбора убран, в истории остался.",
                        verbose_name="archived",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="schools.school",
                        verbose_name="school",
                    ),
                ),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="slot",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="slots",
                to="schedule.room",
                verbose_name="room",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="unique_room_name_per_school"
            ),
        ),
    ]
