# Generated by Django 5.1 on 2026-08-24 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0001_initial"),
        ("schedule", "0018_room_slot_room_room_unique_room_name_per_school"),
        ("schools", "0010_alter_invitation_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Homegroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="homegroups",
                        to="schedule.gradelevel",
                        verbose_name="grade level",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homegroups",
                        to="schools.school",
                        verbose_name="school",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Классный руководитель: кому писать про этот класс.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homegroups_led",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="tutor",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homegroups",
                        to="calendars.schoolyear",
                        verbose_name="school year",
                    ),
                ),
            ],
            options={
                "verbose_name": "homegroup",
                "verbose_name_plural": "homegroups",
                "ordering": ("grade__level", "name"),
            },
        ),
        migrations.CreateModel(
            name="HomegroupStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="removed at"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homegroup_rows_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="added by",
                    ),
                ),
                (
                    "homegroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schedule.homegroup",
                        verbose_name="homegroup",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homegroups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homegroup_rows",
                        to="calendars.schoolyear",
                        verbose_name="school year",
                    ),
                ),
            ],
            options={
                "verbose_name": "homegroup student",
                "verbose_name_plural": "homegroup students",
                "ordering": ("homegroup__name", "student__last_name", "student__email"),
            },
        ),
        migrations.AddConstraint(
            model_name="homegroup",
            constraint=models.UniqueConstraint(
                fields=("school", "year", "name"), name="unique_homegroup_name_per_year"
            ),
        ),
        migrations.AddIndex(
            model_name="homegroupstudent",
            index=models.Index(
                fields=["student", "removed_at"], name="active_homegroup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="homegroupstudent",
            constraint=models.UniqueConstraint(
                fields=("homegroup", "student"), name="one_homegroup_row_per_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="homegroupstudent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("student", "year"),
                name="one_active_homegroup_per_year",
                violation_error_message="This student already belongs to a homegroup this year.",
            ),
        ),
    ]
