# Generated by Django 5.1 on 2026-08-29 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_homegroup_homegroupstudent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='taken at')),
                ('action', models.CharField(max_length=32, verbose_name='action')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='what exactly')),
                ('by_lead', models.BooleanField(default=True, verbose_name='by the course lead')),
                ('batch', models.UUIDField(db_index=True, verbose_name='batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_snapshots', to='schedule.course', verbose_name='course')),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='made by')),
            ],
            options={
                'verbose_name': 'schedule snapshot',
                'verbose_name_plural': 'schedule snapshots',
                'ordering': ('-made_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SlotSnapshotRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.PositiveIntegerField(db_index=True, verbose_name='slot id')),
                ('date', models.DateField(verbose_name='date')),
                ('lesson_number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='cancelled')),
                ('is_extra', models.BooleanField(default=False, verbose_name='extra lesson')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='reason')),
                ('lesson_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='plan row')),
                ('taught_by_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='taught by')),
                ('room_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='room')),
                ('attendance', models.JSONField(blank=True, default=list, verbose_name='attendance')),
                ('works', models.JSONField(blank=True, default=list, verbose_name='works set here')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='schedule.slotsnapshot', verbose_name='snapshot')),
            ],
            options={
                'verbose_name': 'schedule snapshot row',
                'verbose_name_plural': 'schedule snapshot rows',
                'ordering': ('date', 'lesson_number', 'id'),
            },
        ),
    ]
