# Generated by Django 5.1 on 2026-08-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_slotsnapshot_slotsnapshotrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotsnapshot',
            name='undone_action',
            field=models.CharField(blank=True, max_length=32, verbose_name='action being undone'),
        ),
    ]
