# Generated by Django 5.1 on 2026-08-19 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0008_school_ai_month_limit_cents'),
        ('works', '0009_scanpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('scan_header', 'reading a scanned blank header'), ('scan_reread', 're-reading a header that did not add up')], max_length=32, verbose_name='purpose')),
                ('model', models.CharField(max_length=64, verbose_name='model')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='input tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='output tokens')),
                ('cost_micros', models.PositiveIntegerField(default=0, verbose_name='cost, millionths of a dollar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_spend', to='schools.school', verbose_name='school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_spend', to=settings.AUTH_USER_MODEL, verbose_name='who spent it')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_spend', to='works.work', verbose_name='work')),
            ],
            options={
                'verbose_name': 'AI spend',
                'verbose_name_plural': 'AI spend',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['school', 'created_at'], name='vision_aisp_school__08c8f0_idx')],
            },
        ),
    ]
