# Generated by Django 5.1 on 2026-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aispend',
            name='purpose',
            field=models.CharField(choices=[('scan_header', 'reading a scanned blank header'), ('scan_reread', 're-reading a header that did not add up'), ('scan_questions', 'copying the questions off the question paper')], max_length=32, verbose_name='purpose'),
        ),
    ]
