# Generated by Django 5.1 on 2026-08-13 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_course_name'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMethodist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methodists_assigned', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodists', to='schools.school', verbose_name='school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodists', to='schedule.subject', verbose_name='subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodist_of', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'subject methodist',
                'verbose_name_plural': 'subject methodists',
                'ordering': ('subject__name', 'user__last_name'),
                'constraints': [models.UniqueConstraint(fields=('user', 'subject'), name='one_methodist_row_per_subject')],
            },
        ),
    ]
