# Generated by Django 5.1 on 2026-08-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_subjectmethodist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectMethodist',
        ),
    ]
