# Generated by Django 5.1 on 2026-08-14 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_coursestudent'),
        ('schools', '0003_delete_subjectmethodist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Только у ученика: куда записать при первом входе.', related_name='pending_students', to='schedule.course', verbose_name='courses to enrol into'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='kind',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='teacher', help_text='Кем человек войдёт: учителем или учеником.', max_length=8, verbose_name='kind'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(('is_school_admin', True), ('kind', 'student'), _negated=True), name='student_invitation_grants_no_role'),
        ),
    ]
