# Generated by Django 5.1 on 2026-08-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_invitation_courses_invitation_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(blank=True, help_text='Как администратор назвал человека при вводе. Ярлык для списка ожидающих, а не имя учётки: имя приходит из Google при первом входе.', max_length=200, verbose_name='name as written down'),
        ),
    ]
