# Generated by Django 5.1 on 2026-08-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_attendance'),
        ('schools', '0005_invitation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Курсы, которые ждут человека к первому входу. У ученика это «куда записать», у учителя — «что вести»: назначить курс приглашённому надо в тот же день, когда раздают нагрузку, а не когда он соберётся войти.', related_name='pending_invitations', to='schedule.course', verbose_name='courses to join on first sign-in'),
        ),
    ]
