# Generated by Django 5.1 on 2026-08-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_invitations_provision_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ai_month_limit_cents',
            field=models.PositiveIntegerField(default=1000, verbose_name='monthly limit for reading scans, cents'),
        ),
    ]
