# Generated by Django 5.1 on 2026-08-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_ai_month_limit_cents'),
        ('works', '0015_work_is_summative_gradingsystem_gradeband_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='default_grading_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_by', to='works.gradingsystem', verbose_name='recommended grading system'),
        ),
        migrations.AddField(
            model_name='school',
            name='year_grading_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_of', to='works.gradingsystem', verbose_name='grading system for the year result'),
        ),
    ]
