"""
Пригласить можно и родителя.

Вид у приглашения тот же перечень, что у пользователя, — он им и
проставляется при приёме. Данные не трогаются: меняется список допустимых
значений.
"""

# Generated by Django 5.1 on 2026-08-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0009_school_default_grading_system_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("teacher", "teacher"),
                    ("student", "student"),
                    ("parent", "parent"),
                ],
                default="teacher",
                help_text="Кем человек войдёт: учителем или учеником.",
                max_length=8,
                verbose_name="kind",
            ),
        ),
    ]
