# Generated by Django 5.1 on 2026-08-28 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alter_invitation_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='lessons_per_day',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='lessons per day'),
        ),
    ]
