"""
Родитель, как и ученик, не бывает администратором школы.

Ограничение раньше знало только про ученика — родителя тогда не приглашали.
Данные не трогаются: приглашений родителей с ролью в базе быть не может, их
никто не умел выписать.
"""

# Generated by Django 5.1 on 2026-09-07 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0011_school_lessons_per_day"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invitation",
            name="student_invitation_grants_no_role",
        ),
        migrations.AlterField(
            model_name="invitation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("teacher", "teacher"),
                    ("student", "student"),
                    ("parent", "parent"),
                ],
                default="teacher",
                help_text="Кем человек войдёт: учителем, учеником или родителем.",
                max_length=8,
                verbose_name="kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_school_admin", True),
                    ("kind__in", ("student", "parent")),
                    _negated=True,
                ),
                name="family_invitation_grants_no_role",
            ),
        ),
    ]
