"""
Семья: кто чей родитель и о чём родитель говорит с учителем.

Три таблицы. Родство — пара «взрослый и ребёнок», и мама с папой это две
строки, а не одна: у сообщения есть автор, у оповещения получатель, и
ответить на это про «родителя вообще» нельзя. Разговор — тройка «родитель,
учитель, ребёнок»: детей у родителя несколько, и «как у него дела» без имени
не вопрос. Сообщение — строка журнала, как отправка ученика.

Ограничение `nobody_is_their_own_parent` не про опечатку в данных: такая
строка сделала бы ученика собственным представителем и открыла бы ему
родительские разделы.
"""

# Generated by Django 5.1 on 2026-08-23 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_threads_about",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="child",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_threads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="parent",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_threads_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "family thread",
                "verbose_name_plural": "family threads",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="FamilyMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="families.familythread",
                        verbose_name="thread",
                    ),
                ),
            ],
            options={
                "verbose_name": "family message",
                "verbose_name_plural": "family messages",
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Guardianship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="«мама», «папа», «опекун». Пусто — просто представитель.",
                        max_length=32,
                        verbose_name="relation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="child",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "guardianship",
                "verbose_name_plural": "guardianships",
                "ordering": ("child__last_name", "child__email", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="familythread",
            constraint=models.UniqueConstraint(
                fields=("parent", "teacher", "child"),
                name="one_thread_per_parent_teacher_and_child",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianship",
            constraint=models.UniqueConstraint(
                fields=("parent", "child"), name="one_link_per_parent_and_child"
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianship",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("child")), _negated=True),
                name="nobody_is_their_own_parent",
            ),
        ),
    ]
