# Generated by Django 5.1 on 2026-08-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0010_alter_invitation_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talks_about', to=settings.AUTH_USER_MODEL, verbose_name='child talked about')),
                ('lower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks_as_lower', to=settings.AUTH_USER_MODEL, verbose_name='one side')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='schools.school', verbose_name='school')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks_as_upper', to=settings.AUTH_USER_MODEL, verbose_name='the other side')),
            ],
            options={
                'verbose_name': 'talk',
                'verbose_name_plural': 'talks',
                'ordering': ('-updated_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('lower__lt', models.F('upper'))), name='talk_sides_are_ordered'), models.UniqueConstraint(condition=models.Q(('child__isnull', True)), fields=('lower', 'upper'), name='one_talk_per_pair_without_a_child'), models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('lower', 'upper', 'child'), name='one_talk_per_pair_and_child')],
            },
        ),
    ]
