# Generated by Django 5.1 on 2026-08-20 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0009_school_default_grading_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='who declared it')),
            ],
            options={
                'verbose_name': 'family of analogues',
                'verbose_name_plural': 'families of analogues',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='statement, Markdown with LaTeX')),
                ('answer', models.CharField(blank=True, max_length=200, verbose_name='answer, if it is short')),
                ('retired', models.BooleanField(default=False, verbose_name='retired')),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='bank.problem', verbose_name='copied from')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='who created it')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='bank.family', verbose_name='family of analogues')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner; empty means the whole school')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school', verbose_name='school; empty means the system catalogue')),
            ],
            options={
                'verbose_name': 'problem',
                'verbose_name_plural': 'problems',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='short name of the method')),
                ('text', models.TextField(verbose_name='the solution itself, Markdown with LaTeX')),
                ('retired', models.BooleanField(default=False, verbose_name='retired')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='who created it')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner; empty means the whole school')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='bank.problem', verbose_name='problem')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school', verbose_name='school; empty means the system catalogue')),
            ],
            options={
                'verbose_name': 'solution',
                'verbose_name_plural': 'solutions',
                'ordering': ('problem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='author')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='who created it')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner; empty means the whole school')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school', verbose_name='school; empty means the system catalogue')),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bank.section')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bank.source')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('subject', 'предмет: алгебра, геометрия'), ('object', 'объект: пирамида, логарифм'), ('task', 'тип задачи: решить, доказать, вычислить'), ('theorem', 'теорема: Виета, Пифагора'), ('method', 'метод: разложение на множители, замена переменной')], max_length=16, verbose_name='kind')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('retired', models.BooleanField(default=False, verbose_name='retired')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='bank.tag', verbose_name='parent tag, same kind')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ('kind', 'position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SolutionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('uses', 'использует'), ('avoids', 'намеренно обходится')], default='uses', max_length=8, verbose_name='side')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.solution')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.tag')),
            ],
            options={
                'verbose_name': 'tag on a solution',
                'verbose_name_plural': 'tags on solutions',
            },
        ),
        migrations.AddField(
            model_name='solution',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='solutions', through='bank.SolutionTag', to='bank.tag'),
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.tag')),
            ],
            options={
                'verbose_name': 'tag on a problem',
                'verbose_name_plural': 'tags on problems',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems', through='bank.ProblemTag', to='bank.tag'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=32, verbose_name='number as printed')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='page')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bank.problem')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='bank.section')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bank.source')),
            ],
            options={
                'verbose_name': 'problem in a source',
                'verbose_name_plural': 'problems in sources',
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('source', 'problem', 'label'), name='one_place_per_problem_in_a_source')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('kind', 'name'), name='one_tag_name_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='solutiontag',
            constraint=models.UniqueConstraint(fields=('solution', 'tag'), name='one_tag_per_solution'),
        ),
        migrations.AddConstraint(
            model_name='problemtag',
            constraint=models.UniqueConstraint(fields=('problem', 'tag'), name='one_tag_per_problem'),
        ),
    ]
