# Generated by Django 5.1 on 2026-08-20 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtag',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='bank.problem'),
        ),
        migrations.AlterField(
            model_name='problemtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bank.tag'),
        ),
        migrations.AlterField(
            model_name='solutiontag',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='bank.solution'),
        ),
        migrations.AlterField(
            model_name='solutiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bank.tag'),
        ),
    ]
