# Generated by Django 5.1 on 2026-08-20 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_problemtag_problem_alter_problemtag_tag_and_more'),
        ('schools', '0009_school_default_grading_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('expression', models.JSONField(default=dict, verbose_name='expression tree')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='who created it')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner; empty means the whole school')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school', verbose_name='school; empty means the system catalogue')),
            ],
            options={
                'verbose_name': 'saved search',
                'verbose_name_plural': 'saved searches',
                'ordering': ('name', 'id'),
            },
        ),
    ]
