# Generated by Django 5.1 on 2026-08-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_savedsearch'),
        ('plans', '0010_plan_snapshots'),
        ('schedule', '0016_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('closed', models.BooleanField(default=False, verbose_name='closed to what has been covered')),
                ('essence', models.ManyToManyField(blank=True, related_name='topics_needing', to='bank.tag', verbose_name='must use')),
                ('forbidden', models.ManyToManyField(blank=True, related_name='topics_avoiding', to='bank.tag', verbose_name='must avoid')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bank.topic', verbose_name='parent topic')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ('position', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introductions', to='schedule.course', verbose_name='course')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introductions', to='plans.plannode', verbose_name='the lesson that introduces it')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introductions', to='bank.tag')),
            ],
            options={
                'verbose_name': 'tag introduced by a lesson',
                'verbose_name_plural': 'tags introduced by lessons',
                'constraints': [models.UniqueConstraint(fields=('course', 'tag'), name='one_lesson_introduces_a_tag')],
            },
        ),
    ]
