# Generated by Django 5.1 on 2026-08-21 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_problem_and_entry_trees'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='bank.tag', verbose_name='subject'),
        ),
    ]
