# Generated by Django 5.1 on 2026-08-21 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_source_subject'),
        ('schools', '0009_school_default_grading_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('typo', 'опечатка'), ('tag', 'тег'), ('problem', 'задача'), ('solution', 'разбор'), ('other', 'прочее')], max_length=16, verbose_name='kind')),
                ('level', models.CharField(default='school', max_length=16, verbose_name='level')),
                ('text', models.TextField(blank=True, verbose_name='what the person says')),
                ('suggested', models.TextField(blank=True, verbose_name='the text being suggested')),
                ('state', models.CharField(choices=[('pending', 'ждёт'), ('accepted', 'принято'), ('declined', 'отклонено')], default='pending', max_length=16, verbose_name='state')),
                ('answer', models.TextField(blank=True, verbose_name='what the resolver said')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='bank.problem')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='bank.solution')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='bank.tag', verbose_name='the tag being suggested, if it already exists')),
            ],
            options={
                'verbose_name': 'proposal',
                'verbose_name_plural': 'proposals',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProposalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='reply')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bank.proposal')),
            ],
            options={
                'verbose_name': 'note on a proposal',
                'verbose_name_plural': 'notes on proposals',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
