# Generated by Django 5.1 on 2026-08-12 13:00

import calendars.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('weekend_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'понедельник'), (1, 'вторник'), (2, 'среда'), (3, 'четверг'), (4, 'пятница'), (5, 'суббота'), (6, 'воскресенье')]), blank=True, default=calendars.models.default_weekend_days, size=None, verbose_name='weekend weekdays')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='schools.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'school year',
                'verbose_name_plural': 'school years',
                'ordering': ('-start_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('kind', models.CharField(choices=[('holiday', 'public holiday'), ('vacation', 'school break'), ('workday', 'working day')], max_length=16, verbose_name='kind')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='title')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendars.schoolyear', verbose_name='school year')),
            ],
            options={
                'verbose_name': 'calendar exception',
                'verbose_name_plural': 'calendar exceptions',
                'ordering': ('start_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='calendars.schoolyear', verbose_name='school year')),
            ],
            options={
                'verbose_name': 'term',
                'verbose_name_plural': 'terms',
                'ordering': ('start_date', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_year_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='school_year_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='dayexception',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='day_exception_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='term_dates_ordered'),
        ),
    ]
