# Generated by Django 5.1 on 2026-08-11 20:19

import calendars.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('start_date', models.DateField(verbose_name='начало')),
                ('end_date', models.DateField(verbose_name='конец')),
                ('weekend_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'понедельник'), (1, 'вторник'), (2, 'среда'), (3, 'четверг'), (4, 'пятница'), (5, 'суббота'), (6, 'воскресенье')]), blank=True, default=calendars.models.default_weekend_days, size=None, verbose_name='выходные дни недели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'учебный год',
                'verbose_name_plural': 'учебные годы',
                'ordering': ('-start_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='начало')),
                ('end_date', models.DateField(verbose_name='конец')),
                ('kind', models.CharField(choices=[('holiday', 'праздник'), ('vacation', 'каникулы'), ('workday', 'рабочий день')], max_length=16, verbose_name='вид')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='название')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendars.schoolyear', verbose_name='учебный год')),
            ],
            options={
                'verbose_name': 'исключение',
                'verbose_name_plural': 'исключения',
                'ordering': ('start_date', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_school_year_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='school_year_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='dayexception',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='day_exception_dates_ordered'),
        ),
    ]
