# Generated by Django 5.1 on 2026-08-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('start_date', models.DateField(verbose_name='начало')),
                ('end_date', models.DateField(verbose_name='конец')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='calendars.schoolyear', verbose_name='учебный год')),
            ],
            options={
                'verbose_name': 'терм',
                'verbose_name_plural': 'термы',
                'ordering': ('start_date', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='term_dates_ordered')],
            },
        ),
    ]
