# Generated by Django 5.1 on 2026-08-12 11:55

import calendars.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayexception',
            options={'ordering': ('start_date', 'id'), 'verbose_name': 'calendar exception', 'verbose_name_plural': 'calendar exceptions'},
        ),
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ('-start_date', 'name'), 'verbose_name': 'school year', 'verbose_name_plural': 'school years'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ('start_date', 'id'), 'verbose_name': 'term', 'verbose_name_plural': 'terms'},
        ),
        migrations.AlterField(
            model_name='dayexception',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='dayexception',
            name='kind',
            field=models.CharField(choices=[('holiday', 'public holiday'), ('vacation', 'school break'), ('workday', 'working day')], max_length=16, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='dayexception',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='dayexception',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='dayexception',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendars.schoolyear', verbose_name='school year'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='weekend_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'понедельник'), (1, 'вторник'), (2, 'среда'), (3, 'четверг'), (4, 'пятница'), (5, 'суббота'), (6, 'воскресенье')]), blank=True, default=calendars.models.default_weekend_days, size=None, verbose_name='weekend weekdays'),
        ),
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='calendars.schoolyear', verbose_name='school year'),
        ),
    ]
