# Generated by Django 5.1 on 2026-08-12 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('is_section', models.BooleanField(default=False, verbose_name='is a section')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_nodes', to='schedule.course', verbose_name='course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='plans.plannode', verbose_name='section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_nodes', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'plan node',
                'verbose_name_plural': 'lesson plan',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['teacher', 'course', 'parent', 'position'], name='plan_level_idx')],
            },
        ),
    ]
