# Generated by Django 5.1 on 2026-08-11 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0002_lessonslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('is_section', models.BooleanField(default=False, verbose_name='папка')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('kind', models.CharField(choices=[('lesson', 'урок'), ('control', 'контрольная'), ('reserve', 'резерв')], default='lesson', max_length=16, verbose_name='вид')),
                ('note', models.TextField(blank=True, verbose_name='заметка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='plans.plannode', verbose_name='папка')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_nodes', to='schedule.schoolclass', verbose_name='класс')),
            ],
            options={
                'verbose_name': 'узел плана',
                'verbose_name_plural': 'учебный план',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['school_class', 'parent', 'position'], name='plan_level_idx')],
            },
        ),
    ]
