# Generated by Django 5.1 on 2026-08-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannode',
            name='kind',
        ),
    ]
