# Generated by Django 5.1 on 2026-08-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannode',
            name='body',
            field=models.TextField(blank=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='plannode',
            name='formative',
            field=models.TextField(blank=True, verbose_name='formative check'),
        ),
        migrations.AddField(
            model_name='plannode',
            name='homework',
            field=models.TextField(blank=True, verbose_name='homework'),
        ),
        migrations.AddField(
            model_name='plannode',
            name='objectives',
            field=models.TextField(blank=True, verbose_name='objectives'),
        ),
    ]
