# Generated by Django 5.1 on 2026-08-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plannode_kind'),
        ('schedule', '0003_alter_lessonslot_options_alter_schoolclass_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannode',
            options={'ordering': ('position', 'id'), 'verbose_name': 'plan node', 'verbose_name_plural': 'lesson plan'},
        ),
        migrations.AlterField(
            model_name='plannode',
            name='is_section',
            field=models.BooleanField(default=False, verbose_name='is a section'),
        ),
        migrations.AlterField(
            model_name='plannode',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='plannode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='plans.plannode', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='plannode',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='plannode',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_nodes', to='schedule.schoolclass', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='plannode',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
