# Generated by Django 5.1 on 2026-08-13 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_lesson_content'),
        ('schedule', '0006_alter_course_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fixed at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_baselines', to='schedule.course', verbose_name='course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_baselines', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'plan baseline',
                'verbose_name_plural': 'plan baselines',
            },
        ),
        migrations.CreateModel(
            name='PlanBaselineRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='position')),
                ('is_section', models.BooleanField(default=False, verbose_name='section')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('node_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='plan node id')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='plans.planbaseline', verbose_name='baseline')),
            ],
            options={
                'verbose_name': 'plan baseline row',
                'verbose_name_plural': 'plan baseline rows',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='planbaseline',
            constraint=models.UniqueConstraint(fields=('teacher', 'course'), name='one_baseline_per_plan'),
        ),
    ]
