# Generated by Django 5.1 on 2026-08-13 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_planbaseline_planbaselinerow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planbaseline',
            options={'ordering': ('-created_at',), 'verbose_name': 'plan baseline', 'verbose_name_plural': 'plan baselines'},
        ),
        migrations.RemoveConstraint(
            model_name='planbaseline',
            name='one_baseline_per_plan',
        ),
        migrations.AddField(
            model_name='planbaseline',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved at'),
        ),
        migrations.AddField(
            model_name='planbaseline',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='planbaseline',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_to_review', to=settings.AUTH_USER_MODEL, verbose_name='reviewer'),
        ),
        migrations.AddField(
            model_name='planbaseline',
            name='status',
            field=models.CharField(choices=[('draft', 'withdrawn by an edit'), ('pending', 'waiting for approval'), ('approved', 'approved'), ('returned', 'returned with a comment')], default='pending', max_length=16, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='planbaseline',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submitted at'),
        ),
        migrations.AlterField(
            model_name='planbaseline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='snapshot taken at'),
        ),
    ]
