# Generated by Django 5.1 on 2026-08-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_planbaseline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planbaseline',
            name='status',
            field=models.CharField(choices=[('pending', 'waiting for approval'), ('approved', 'approved'), ('returned', 'returned with a comment')], default='pending', max_length=16, verbose_name='status'),
        ),
    ]
