# Generated by Django 5.1 on 2026-08-14 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_planbaseline_status'),
        ('schedule', '0008_coursestudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='planbaseline',
            index=models.Index(fields=['teacher', 'course', 'status'], name='baseline_owner_status_idx'),
        ),
    ]
