# Generated by Django 5.1 on 2026-08-14 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def one_plan_per_course(apps, schema_editor):
    """
    Проверка перед тем, как план потеряет владельца.

    Если в курсе лежат строки от двух учителей — это две программы под одним
    именем, и выбрать за школу, какая настоящая, миграция не вправе. Она
    останавливается и называет курсы: разобрать их надо руками — лишний план
    снимается в библиотеку («снять шаблон с плана»), и работа не пропадает.

    На всех известных базах конфликтов нет, и проверка проходит молча. Она
    здесь на случай, если между этой правкой и выкаткой кто-то заведёт
    второй план: молча потерять его хуже, чем не выкатиться.
    """
    PlanNode = apps.get_model("plans", "PlanNode")

    owners = {}
    for course_id, teacher_id in PlanNode.objects.values_list(
        "course_id", "teacher_id"
    ).distinct():
        owners.setdefault(course_id, set()).add(teacher_id)

    shared = {course: people for course, people in owners.items() if len(people) > 1}
    if shared:
        raise RuntimeError(
            "в этих курсах планы сразу нескольких учителей, и выбрать за "
            f"школу нельзя: {shared}. Снимите лишние планы в библиотеку и "
            "удалите их из курса, потом повторите миграцию"
        )


def keep_who_submitted(apps, schema_editor):
    """Владельца у эталона больше нет, но кто его прислал — история."""
    PlanBaseline = apps.get_model("plans", "PlanBaseline")

    for baseline in PlanBaseline.objects.all():
        baseline.submitted_by_id = baseline.teacher_id
        baseline.save(update_fields=["submitted_by"])


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_planbaseline_baseline_owner_status_idx'),
        ('schedule', '0009_remove_courseassignment_unique_course_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(one_plan_per_course, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='planbaseline',
            name='baseline_owner_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='plannode',
            name='plan_level_idx',
        ),
        migrations.AddField(
            model_name='planbaseline',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_baselines', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.RunPython(keep_who_submitted, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='planbaseline',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='plannode',
            name='teacher',
        ),
        migrations.AddIndex(
            model_name='planbaseline',
            index=models.Index(fields=['course', 'status'], name='baseline_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='plannode',
            index=models.Index(fields=['course', 'parent', 'position'], name='plan_level_idx'),
        ),
    ]
