# Generated by Django 5.1 on 2026-08-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_remove_planbaseline_baseline_owner_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planbaseline',
            name='slots_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='hours at approval'),
        ),
    ]
