# Generated by Django 5.1 on 2026-08-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_baseline_slots_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='planbaselinerow',
            name='content_hash',
            field=models.CharField(blank=True, max_length=32, verbose_name='content hash'),
        ),
    ]
