# Generated by Django 5.1 on 2026-08-18 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_attachment_text_kind'),
        ('plans', '0009_planbaselinerow_content_hash'),
        ('schedule', '0016_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='taken at')),
                ('action', models.CharField(help_text='Машинный код действия: по нему кнопка отмены называет себя.', max_length=32, verbose_name='what happened next')),
                ('detail', models.CharField(blank=True, help_text='Название строки или файла — чтобы «отменить» называло, что именно.', max_length=200, verbose_name='what it touched')),
                ('by_lead', models.BooleanField(default=True, help_text='Правил ли курс его собственный ведущий. Снимок чужой правки живёт дольше и показывается учителю пометкой: он про неё иначе не узнает.', verbose_name='made by the lead teacher')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='schedule.course', verbose_name='course')),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='about to edit')),
            ],
            options={
                'verbose_name': 'plan snapshot',
                'verbose_name_plural': 'plan snapshots',
                'ordering': ('-made_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PlanSnapshotRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.PositiveIntegerField(verbose_name='plan node id')),
                ('parent_node_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='parent node id')),
                ('position', models.PositiveIntegerField(verbose_name='position')),
                ('is_section', models.BooleanField(default=False, verbose_name='section')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('objectives', models.TextField(blank=True, verbose_name='objectives')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('formative', models.TextField(blank=True, verbose_name='formative check')),
                ('homework', models.TextField(blank=True, verbose_name='homework')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='plans.plansnapshot', verbose_name='snapshot')),
            ],
            options={
                'verbose_name': 'plan snapshot row',
                'verbose_name_plural': 'plan snapshot rows',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlanSnapshotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=8, verbose_name='kind')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='external address')),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_links', to='files.storedfile', verbose_name='stored file')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='plans.plansnapshotrow', verbose_name='row')),
            ],
            options={
                'verbose_name': 'plan snapshot attachment',
                'verbose_name_plural': 'plan snapshot attachments',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='plansnapshot',
            index=models.Index(fields=['course', '-made_at'], name='plans_plans_course__66ea90_idx'),
        ),
    ]
