# Generated by Django 5.1 on 2026-08-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_plan_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansnapshotfile',
            name='inline',
            field=models.BooleanField(default=False, verbose_name='inline in the text'),
        ),
    ]
