# Generated by Django 5.1 on 2026-08-29 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_plantemplate_is_live_and_more'),
        ('plans', '0011_plansnapshotfile_inline'),
        ('schedule', '0020_slotsnapshot_slotsnapshotrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannode',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='library.plantemplate', verbose_name='library template'),
        ),
        migrations.AlterField(
            model_name='plannode',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_nodes', to='schedule.course', verbose_name='course'),
        ),
        migrations.AddIndex(
            model_name='plannode',
            index=models.Index(fields=['template', 'parent', 'position'], name='plan_template_level_idx'),
        ),
        migrations.AddConstraint(
            model_name='plannode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('template__isnull', True)), models.Q(('course__isnull', True), ('template__isnull', False)), _connector='OR'), name='plan_node_has_exactly_one_owner'),
        ),
    ]
