# Generated by Django 5.1 on 2026-08-29 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_plantemplate_is_live_and_more'),
        ('plans', '0012_plan_node_owner'),
        ('schedule', '0020_slotsnapshot_slotsnapshotrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plansnapshot',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='library.plantemplate', verbose_name='library template'),
        ),
        migrations.AlterField(
            model_name='plansnapshot',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='schedule.course', verbose_name='course'),
        ),
        migrations.AddIndex(
            model_name='plansnapshot',
            index=models.Index(fields=['template', '-made_at'], name='snapshot_template_idx'),
        ),
        migrations.AddConstraint(
            model_name='plansnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('template__isnull', True)), models.Q(('course__isnull', True), ('template__isnull', False)), _connector='OR'), name='plan_snapshot_has_exactly_one_owner'),
        ),
    ]
