# Generated by Django 5.1 on 2026-08-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_template_rows_become_plan_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannode',
            name='origin_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='copied from this row'),
        ),
    ]
