# Generated by Django 5.1 on 2026-08-29 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_proposals'),
        ('plans', '0015_plannode_origin_id'),
        ('schedule', '0020_slotsnapshot_slotsnapshotrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSnapshotIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_introductions', to='schedule.course', verbose_name='course')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introductions', to='plans.plansnapshotrow', verbose_name='row')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_introductions', to='bank.tag', verbose_name='tag introduced here')),
            ],
            options={
                'verbose_name': 'plan snapshot introduction',
                'verbose_name_plural': 'plan snapshot introductions',
                'ordering': ('id',),
            },
        ),
    ]
