# Generated by Django 5.1 on 2026-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_plansnapshotintroduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansnapshotrow',
            name='origin_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='origin row id'),
        ),
    ]
