# Generated by Django 5.1 on 2026-08-29 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_delete_plantemplaterow'),
        ('plans', '0017_plansnapshotrow_origin_id'),
        ('schedule', '0020_slotsnapshot_slotsnapshotrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansnapshot',
            name='abandoned',
            field=models.BooleanField(default=False, help_text='Отошли назад по ленте и стали править оттуда — всё, что было впереди, ходом больше не достижимо. Помечается, а не удаляется на месте: среди брошенного бывает запись о чужой правке, а она девяносто дней и есть аудит, а не удобство. Остальное уносит обычная уборка при следующей записи.', verbose_name='no longer on the live timeline'),
        ),
        migrations.CreateModel(
            name='PlanUndoCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursors', to='plans.plansnapshot', verbose_name='showing this state')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='undo_cursor', to='schedule.course', verbose_name='course')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='undo_cursor', to='library.plantemplate', verbose_name='library template')),
            ],
            options={
                'verbose_name': 'plan undo cursor',
                'verbose_name_plural': 'plan undo cursors',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('template__isnull', True)), models.Q(('course__isnull', True), ('template__isnull', False)), _connector='OR'), name='plan_undo_cursor_has_exactly_one_owner'), models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course',), name='one_undo_cursor_per_course'), models.UniqueConstraint(condition=models.Q(('template__isnull', False)), fields=('template',), name='one_undo_cursor_per_template')],
            },
        ),
    ]
