proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
# по нему Django понимает, что снаружи был https (SECURE_PROXY_SSL_HEADER)
proxy_set_header X-Forwarded-Proto $scheme;
proxy_redirect off;
