# Generated by Django 5.1 on 2026-08-14 13:46

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0006_planbaseline_baseline_owner_status_idx'),
        ('schedule', '0008_coursestudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('opens_at', models.DateTimeField(help_text='До этого момента работы для ученика не существует.', verbose_name='opens at')),
                ('closes_at', models.DateTimeField(help_text='После этого момента ответы не принимаются, но всё видно.', verbose_name='closes at')),
                ('attempts', models.PositiveSmallIntegerField(blank=True, help_text='Пусто — без ограничения. Считается по задаче, не по работе.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='attempts per task')),
                ('show_result', models.BooleanField(default=True, help_text='Видит ли ученик отметку учителя сразу, как только она поставлена. Выключено — увидит после закрытия окна.', verbose_name='show the verdict to the student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='schedule.course', verbose_name='course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='plans.plannode', verbose_name='lesson of the plan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
                'ordering': ('-opens_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('question', models.TextField(verbose_name='question')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Хранятся ровно как введены: обработка — при сравнении.', size=None, verbose_name='accepted answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='works.work', verbose_name='work')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='answer as it was typed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(blank=True, help_text='Пусто — не проверено. Смена отметки попытку не расходует.', null=True, verbose_name='verdict')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='checked at')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_submissions', to=settings.AUTH_USER_MODEL, verbose_name='checked by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='works.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['task', 'student', 'created_at'], name='submission_cell_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['course', 'opens_at'], name='work_course_opens_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['teacher', 'course'], name='work_owner_idx'),
        ),
    ]
