# Generated by Django 5.1 on 2026-08-15 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_work_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('name', models.CharField(blank=True, help_text='Пустое у обычной отметки; «Критерий A» и подобное — у MYP.', max_length=100, verbose_name='name')),
                ('maximum', models.PositiveSmallIntegerField(help_text='Верх шкалы: 5, 8, 100 — как решила школа.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='maximum')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='works.work', verbose_name='work')),
            ],
            options={
                'verbose_name': 'grading criterion',
                'verbose_name_plural': 'grading criteria',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Слова учителя об этой работе. Бывают и без оценки.', verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_works', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='works.work', verbose_name='work')),
            ],
            options={
                'verbose_name': "student's work",
                'verbose_name_plural': "students' works",
                'ordering': ('student__last_name', 'student__email'),
            },
        ),
        migrations.CreateModel(
            name='MarkChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='value')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='works.criterion', verbose_name='criterion')),
                ('student_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='works.studentwork', verbose_name="student's work")),
            ],
            options={
                'verbose_name': 'mark change',
                'verbose_name_plural': 'mark changes',
                'ordering': ('changed_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='value')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='works.criterion', verbose_name='criterion')),
                ('student_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='works.studentwork', verbose_name="student's work")),
            ],
            options={
                'verbose_name': 'mark',
                'verbose_name_plural': 'marks',
                'ordering': ('criterion__position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='studentwork',
            constraint=models.UniqueConstraint(fields=('work', 'student'), name='one_row_per_student_per_work'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('student_work', 'criterion'), name='one_mark_per_criterion'),
        ),
    ]
