# Generated by Django 5.1 on 2026-08-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_criterion_studentwork_markchange_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='on_paper',
            field=models.BooleanField(default=False, help_text='Работа написана на бумаге: задач и отправок у неё нет, у каждого ученика скан.', verbose_name='written on paper'),
        ),
    ]
