# Generated by Django 5.1 on 2026-08-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_work_on_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, help_text='Что делать: текст работы целиком. У домашнего задания это оно и есть, у контрольной — обычно пусто.', verbose_name='description'),
        ),
    ]
