# Generated by Django 5.1 on 2026-08-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_rename_work_lesson_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_homework',
            field=models.BooleanField(default=False, help_text='Задано на дом. Отдельная работа от классной ничем, кроме этого, не отличается — признак нужен, чтобы показать её в своём разделе урока: пустая домашняя и пустая классная в данных неразличимы.', verbose_name='homework'),
        ),
    ]
