# Generated by Django 5.1 on 2026-08-19 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_work_is_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='page number in the upload, from zero')),
                ('fingerprint', models.CharField(blank=True, max_length=64, verbose_name='sha256 of the strip')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='first name as read')),
                ('surname', models.CharField(blank=True, max_length=200, verbose_name='surname as read')),
                ('date_text', models.CharField(blank=True, max_length=64, verbose_name='date as written')),
                ('cells', models.JSONField(blank=True, default=list, verbose_name='cells as read')),
                ('model', models.CharField(blank=True, max_length=64, verbose_name='model that read it')),
                ('decided_by_human', models.BooleanField(default=False, verbose_name='assigned by a human')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_pages', to=settings.AUTH_USER_MODEL, verbose_name='whose page')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_pages', to='works.work', verbose_name='work')),
            ],
            options={
                'verbose_name': 'scanned page',
                'verbose_name_plural': 'scanned pages',
                'ordering': ('work', 'index'),
                'constraints': [models.UniqueConstraint(fields=('work', 'index'), name='one_row_per_scanned_page')],
            },
        ),
    ]
