# Generated by Django 5.1 on 2026-08-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_scanpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpage',
            name='guess',
            field=models.CharField(blank=True, max_length=200, verbose_name="model's guess from the roster"),
        ),
    ]
