# Generated by Django 5.1 on 2026-08-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_scanpage_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpage',
            name='headerless',
            field=models.BooleanField(default=False, verbose_name='no header found on the page'),
        ),
    ]
