# Generated by Django 5.1 on 2026-08-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_scanpage_headerless'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpage',
            name='ours',
            field=models.BooleanField(default=False, verbose_name='our blank, by the mark in the corner'),
        ),
    ]
