# Generated by Django 5.1 on 2026-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_scanpage_ours'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='question',
            field=models.TextField(blank=True, verbose_name='question as printed on the paper'),
        ),
    ]
