# Generated by Django 5.1 on 2026-08-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_criterion_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ('criterion__position', 'task__position', 'id'), 'verbose_name': 'mark', 'verbose_name_plural': 'marks'},
        ),
        migrations.AddField(
            model_name='mark',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='works.task', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='markchange',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_changes', to='works.task', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='task',
            name='maximum',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='top mark for this question'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='works.criterion', verbose_name='criterion'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.PositiveSmallIntegerField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='markchange',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_changes', to='works.criterion', verbose_name='criterion'),
        ),
        migrations.AlterField(
            model_name='markchange',
            name='student_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_changes', to='works.studentwork', verbose_name="student's work"),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('student_work', 'task'), name='one_mark_per_question'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('criterion__isnull', True), ('task__isnull', False)), models.Q(('criterion__isnull', False), ('task__isnull', True)), _connector='OR'), name='mark_belongs_to_one_axis'),
        ),
    ]
