# Generated by Django 5.1 on 2026-08-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_ai_month_limit_cents'),
        ('works', '0014_alter_mark_options_mark_task_markchange_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_summative',
            field=models.BooleanField(default=False, help_text='Формативную оценивают как придётся, и в итог она не идёт.', verbose_name='counts towards the term result'),
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('kind', models.CharField(choices=[('points', 'sum of question marks, bands in percent'), ('levels', 'levels per criterion, bands on the sum'), ('passfail', 'pass or fail')], default='points', max_length=16, verbose_name='kind')),
                ('top_level', models.PositiveSmallIntegerField(default=8, verbose_name='top level per criterion')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='teachers may choose it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_systems', to='schools.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'grading system',
                'verbose_name_plural': 'grading systems',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('label', models.CharField(max_length=32, verbose_name='what is shown')),
                ('threshold', models.PositiveSmallIntegerField(default=0, verbose_name='from this value up')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='works.gradingsystem', verbose_name='system')),
            ],
            options={
                'verbose_name': 'grade band',
                'verbose_name_plural': 'grade bands',
                'ordering': ('-threshold', 'position'),
            },
        ),
        migrations.AddField(
            model_name='work',
            name='grading_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.gradingsystem', verbose_name='grading system'),
        ),
        migrations.AddConstraint(
            model_name='gradingsystem',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='one_grading_system_name_per_school'),
        ),
    ]
