# Generated by Django 5.1 on 2026-08-20 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_topic_introduction'),
        ('works', '0016_thread_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked_in', to='bank.problem', verbose_name='problem it was taken from'),
        ),
    ]
