# Generated by Django 5.1 on 2026-08-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0019_drop_statement_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='show_stem',
            field=models.BooleanField(default=True, verbose_name='show the stem to the student'),
        ),
    ]
