# Generated by Django 5.1 on 2026-08-22 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0020_task_show_stem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Ответ, за который поставлен балл. Пусто — работа на бумаге.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='works.submission', verbose_name='submission'),
        ),
    ]
