# Generated by Django 5.1 on 2026-08-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0022_verdict_becomes_a_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_correct',
        ),
    ]
