# Generated by Django 5.1 on 2026-08-23 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_photo_of_a_students_work'),
        ('works', '0027_task_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoStroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#e11d48', max_length=7, verbose_name='colour')),
                ('width', models.PositiveSmallIntegerField(verbose_name='pen width, per mille of the width')),
                ('points', models.JSONField(default=list, verbose_name='points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'stroke on a photo',
                'verbose_name_plural': 'strokes on photos',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='works.thread', verbose_name='thread'),
        ),
        migrations.CreateModel(
            name='PhotoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='x, share of the width')),
                ('y', models.FloatField(verbose_name='y, share of the height')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='files.attachment', verbose_name='photo')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_notes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'note on a photo',
                'verbose_name_plural': 'notes on photos',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='message',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='works.photonote', verbose_name='note on a photo'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('note__isnull', True), ('thread__isnull', False)), models.Q(('note__isnull', False), ('thread__isnull', True)), _connector='OR'), name='message_belongs_to_one_conversation'),
        ),
        migrations.AddField(
            model_name='photostroke',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strokes', to='files.attachment', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='photostroke',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_strokes', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddIndex(
            model_name='photonote',
            index=models.Index(fields=['attachment', 'id'], name='note_photo_idx'),
        ),
        migrations.AddIndex(
            model_name='photostroke',
            index=models.Index(fields=['attachment', 'id'], name='stroke_photo_idx'),
        ),
    ]
