# Generated by Django 5.1 on 2026-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0028_markup_on_a_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='grade',
            field=models.CharField(blank=True, help_text='Итог, поставленный руками. Пусто — считает система по своим полосам; заполнено — показывается это, а не выведенное.', max_length=40, verbose_name='final grade set by the teacher'),
        ),
    ]
