# Generated by Django 5.1 on 2026-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0029_the_teacher_has_the_last_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, help_text='Текст задания: то, что ученик видит над задачами, и то же самое видит над ними учитель. Задачи при этом необязательны — задание целиком бывает написано здесь, а решения приходят снимками.', verbose_name='description'),
        ),
    ]
