# Generated by Django 5.1 on 2026-08-25 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_homegroup_homegroupstudent_and_more'),
        ('works', '0032_a_mark_knows_which_page_it_is_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written', models.CharField(max_length=200, verbose_name='as the reader saw it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_aliases', to='schedule.course', verbose_name='course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_aliases', to=settings.AUTH_USER_MODEL, verbose_name='who it turned out to be')),
            ],
            options={
                'verbose_name': 'remembered handwriting',
                'verbose_name_plural': 'remembered handwriting',
                'ordering': ('course', 'written'),
                'constraints': [models.UniqueConstraint(fields=('course', 'written'), name='one_alias_per_writing')],
            },
        ),
    ]
