# Generated by Django 5.1 on 2026-08-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_a_talk_is_two_people'),
        ('works', '0033_scanalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='message_belongs_to_one_conversation',
        ),
        migrations.AddField(
            model_name='message',
            name='talk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='talks.talk', verbose_name='talk'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('note__isnull', True), ('talk__isnull', True), ('thread__isnull', False)), models.Q(('note__isnull', False), ('talk__isnull', True), ('thread__isnull', True)), models.Q(('note__isnull', True), ('talk__isnull', False), ('thread__isnull', True)), _connector='OR'), name='message_belongs_to_one_conversation'),
        ),
    ]
