# Generated by Django 5.1 on 2026-08-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0034_a_message_belongs_to_a_talk_too'),
    ]

    operations = [
        migrations.AddField(
            model_name='markchange',
            name='label',
            field=models.CharField(blank=True, max_length=40, verbose_name='final grade as set'),
        ),
    ]
