# Generated by Django 5.1 on 2026-08-26 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alter_invitation_kind'),
        ('works', '0035_the_final_grade_is_an_event_too'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('label', models.CharField(max_length=4, verbose_name='short label for the gradebook')),
                ('color', models.CharField(choices=[('slate', 'slate'), ('blue', 'blue'), ('green', 'green'), ('amber', 'amber'), ('violet', 'violet'), ('red', 'red')], default='slate', max_length=16, verbose_name='colour')),
                ('counts_to_term', models.BooleanField(default=False, help_text='Умолчание для новой работы этого вида; решает всё равно учитель.', verbose_name='counts towards the term result by default')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='teachers may choose it')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_kinds', to='schools.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'kind of work',
                'verbose_name_plural': 'kinds of work',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AddField(
            model_name='work',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.workkind', verbose_name='kind of work'),
        ),
        migrations.AddConstraint(
            model_name='workkind',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='one_work_kind_name_per_school'),
        ),
    ]
