# Generated by Django 5.1 on 2026-08-12 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_lesson_content'),
        ('plans', '0002_lesson_content'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=400, unique=True, verbose_name='object key')),
                ('original_name', models.CharField(max_length=255, verbose_name='original name')),
                ('size', models.PositiveIntegerField(verbose_name='size, bytes')),
                ('content_type', models.CharField(max_length=120, verbose_name='content type')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='sha256')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='schools.school', verbose_name='school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'stored file',
                'verbose_name_plural': 'stored files',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'file'), ('link', 'link')], default='file', max_length=8, verbose_name='kind')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='address')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plans.plannode', verbose_name='plan lesson')),
                ('template_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='library.plantemplaterow', verbose_name='template row')),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='files.storedfile', verbose_name='file')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['school', 'checksum', 'size'], name='stored_file_dedup_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['plan_row', 'position'], name='attachment_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['template_row', 'position'], name='attachment_template_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('plan_row__isnull', False), ('template_row__isnull', True)), models.Q(('plan_row__isnull', True), ('template_row__isnull', False)), _connector='OR'), name='attachment_has_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'file'), ('stored_file__isnull', False)), models.Q(('kind', 'link'), ('stored_file__isnull', True)), _connector='OR'), name='attachment_kind_matches_target'),
        ),
    ]
