# Generated by Django 5.1 on 2026-08-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('library', '0003_alter_plantemplate_grade'),
        ('plans', '0007_remove_planbaseline_baseline_owner_status_idx_and_more'),
        ('works', '0004_criterion_studentwork_markchange_mark_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachment',
            name='attachment_has_exactly_one_owner',
        ),
        migrations.AddField(
            model_name='attachment',
            name='student_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='works.studentwork', verbose_name="student's work"),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['student_work', 'position'], name='attachment_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('plan_row__isnull', False), ('student_work__isnull', True), ('template_row__isnull', True)), models.Q(('plan_row__isnull', True), ('student_work__isnull', True), ('template_row__isnull', False)), models.Q(('plan_row__isnull', True), ('student_work__isnull', False), ('template_row__isnull', True)), _connector='OR'), name='attachment_has_exactly_one_owner'),
        ),
    ]
