# Generated by Django 5.1 on 2026-08-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_attachment_attachment_has_exactly_one_owner_and_more'),
        ('library', '0003_alter_plantemplate_grade'),
        ('plans', '0008_baseline_slots_total'),
        ('works', '0008_work_is_homework'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachment',
            name='attachment_kind_matches_target',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('file', 'file'), ('link', 'link'), ('text', 'text')], default='file', max_length=8, verbose_name='kind'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'file'), ('stored_file__isnull', False)), models.Q(('kind', 'link'), ('stored_file__isnull', True)), models.Q(('kind', 'text'), ('stored_file__isnull', True), ('url', '')), _connector='OR'), name='attachment_kind_matches_target'),
        ),
    ]
