# Generated by Django 5.1 on 2026-08-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_attachment_text_kind'),
        ('library', '0003_alter_plantemplate_grade'),
        ('plans', '0011_plansnapshotfile_inline'),
        ('works', '0027_task_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='inline',
            field=models.BooleanField(default=False, verbose_name='inline in the text'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('inline', False), ('kind', 'file'), _connector='OR'), name='inline_attachment_is_a_file'),
        ),
    ]
