# Generated by Django 5.1 on 2026-08-23 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_attachment_inline_and_more'),
        ('library', '0003_alter_plantemplate_grade'),
        ('plans', '0011_plansnapshotfile_inline'),
        ('works', '0027_task_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_added', to=settings.AUTH_USER_MODEL, verbose_name='added by'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='rotation',
            field=models.PositiveSmallIntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0, verbose_name='rotation, degrees clockwise'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='works.task', verbose_name='question inside the work'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['task', 'position'], name='attachment_task_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('task__isnull', True), ('student_work__isnull', False), _connector='OR'), name='attachment_task_lives_inside_a_students_work'),
        ),
    ]
