# Generated by Django 5.1 on 2026-08-23 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_photo_of_a_students_work'),
        ('library', '0003_alter_plantemplate_grade'),
        ('plans', '0011_plansnapshotfile_inline'),
        ('works', '0028_markup_on_a_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachment',
            name='attachment_has_exactly_one_owner',
        ),
        migrations.AddField(
            model_name='attachment',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='works.work', verbose_name='work'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['work', 'position'], name='attachment_work_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('plan_row__isnull', False), ('student_work__isnull', True), ('template_row__isnull', True), ('work__isnull', True)), models.Q(('plan_row__isnull', True), ('student_work__isnull', True), ('template_row__isnull', False), ('work__isnull', True)), models.Q(('plan_row__isnull', True), ('student_work__isnull', False), ('template_row__isnull', True), ('work__isnull', True)), models.Q(('plan_row__isnull', True), ('student_work__isnull', True), ('template_row__isnull', True), ('work__isnull', False)), _connector='OR'), name='attachment_has_exactly_one_owner'),
        ),
    ]
