# Generated by Django 5.1 on 2026-08-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_attachment_on_the_work_itself'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='staff_only',
            field=models.BooleanField(default=False, verbose_name='teachers only'),
        ),
    ]
