# Generated by Django 5.1 on 2026-08-27 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
        ("files", "0007_the_pile_is_the_teachers_alone"),
        ("library", "0004_plantemplate_is_live_and_more"),
        ("plans", "0011_plansnapshotfile_inline"),
        ("works", "0036_the_school_says_what_kinds_of_work_it_has"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attachment",
            name="attachment_has_exactly_one_owner",
        ),
        migrations.AddField(
            model_name="attachment",
            name="bookmark_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="bookmarks.folder",
                verbose_name="folder on that shelf",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="bookmark_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="personal shelf of",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="note",
            field=models.TextField(blank=True, verbose_name="note"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["bookmark_owner", "position"], name="attachment_shelf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("bookmark_owner__isnull", True),
                        ("plan_row__isnull", False),
                        ("student_work__isnull", True),
                        ("template_row__isnull", True),
                        ("work__isnull", True),
                    ),
                    models.Q(
                        ("bookmark_owner__isnull", True),
                        ("plan_row__isnull", True),
                        ("student_work__isnull", True),
                        ("template_row__isnull", False),
                        ("work__isnull", True),
                    ),
                    models.Q(
                        ("bookmark_owner__isnull", True),
                        ("plan_row__isnull", True),
                        ("student_work__isnull", False),
                        ("template_row__isnull", True),
                        ("work__isnull", True),
                    ),
                    models.Q(
                        ("bookmark_owner__isnull", True),
                        ("plan_row__isnull", True),
                        ("student_work__isnull", True),
                        ("template_row__isnull", True),
                        ("work__isnull", False),
                    ),
                    models.Q(
                        ("bookmark_owner__isnull", False),
                        ("plan_row__isnull", True),
                        ("student_work__isnull", True),
                        ("template_row__isnull", True),
                        ("work__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="attachment_has_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("bookmark_folder__isnull", True),
                    ("bookmark_owner__isnull", False),
                    _connector="OR",
                ),
                name="attachment_folder_lives_on_a_personal_shelf",
            ),
        ),
    ]
