# Generated by Django 5.1 on 2026-08-27 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
        ("files", "0008_the_personal_shelf"),
        ("library", "0004_plantemplate_is_live_and_more"),
        ("plans", "0011_plansnapshotfile_inline"),
        ("schools", "0010_alter_invitation_kind"),
        ("works", "0036_the_school_says_what_kinds_of_work_it_has"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attachment",
            name="attachment_has_exactly_one_owner",
        ),
        migrations.AddField(
            model_name="attachment",
            name="school_shelf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shelf_items",
                to="schools.school",
                verbose_name="shelf of the school",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["school_shelf", "position"], name="attachment_school_shelf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("bookmark_owner__isnull", True),
                        ("plan_row__isnull", False),
                        ("school_shelf__isnull", True),
                        ("student_work__isnull", True),
                        ("template_row__isnull", True),
                        ("work__isnull", True),
                    ),
                    models.Q(
                        ("bookmark_owner__isnull", True),
                        ("plan_row__isnull", True),
                        ("school_shelf__isnull", True),
                        ("student_work__isnull", True),
                        ("template_row__isnull", False),
                        ("work__isnull", True),
                    ),
                    models.Q(
                        ("bookmark_owner__isnull", True),
                        ("plan_row__isnull", True),
                        ("school_shelf__isnull", True),
                        ("student_work__isnull", False),
                        ("template_row__isnull", True),
                        ("work__isnull", True),
                    ),
                    models.Q(
                        ("bookmark_owner__isnull", True),
                        ("plan_row__isnull", True),
                        ("school_shelf__isnull", True),
                        ("student_work__isnull", True),
                        ("template_row__isnull", True),
                        ("work__isnull", False),
                    ),
                    models.Q(
                        ("bookmark_owner__isnull", False),
                        ("plan_row__isnull", True),
                        ("school_shelf__isnull", True),
                        ("student_work__isnull", True),
                        ("template_row__isnull", True),
                        ("work__isnull", True),
                    ),
                    models.Q(
                        ("bookmark_owner__isnull", True),
                        ("plan_row__isnull", True),
                        ("school_shelf__isnull", False),
                        ("student_work__isnull", True),
                        ("template_row__isnull", True),
                        ("work__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="attachment_has_exactly_one_owner",
            ),
        ),
    ]
