# Generated by Django 5.1 on 2026-08-29 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
        ('files', '0009_the_school_shelf'),
        ('plans', '0014_template_rows_become_plan_nodes'),
        ('schools', '0011_school_lessons_per_day'),
        ('works', '0036_the_school_says_what_kinds_of_work_it_has'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachment',
            name='attachment_has_exactly_one_owner',
        ),
        migrations.RemoveIndex(
            model_name='attachment',
            name='attachment_template_idx',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='template_row',
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bookmark_owner__isnull', True), ('plan_row__isnull', False), ('school_shelf__isnull', True), ('student_work__isnull', True), ('work__isnull', True)), models.Q(('bookmark_owner__isnull', True), ('plan_row__isnull', True), ('school_shelf__isnull', True), ('student_work__isnull', False), ('work__isnull', True)), models.Q(('bookmark_owner__isnull', True), ('plan_row__isnull', True), ('school_shelf__isnull', True), ('student_work__isnull', True), ('work__isnull', False)), models.Q(('bookmark_owner__isnull', False), ('plan_row__isnull', True), ('school_shelf__isnull', True), ('student_work__isnull', True), ('work__isnull', True)), models.Q(('bookmark_owner__isnull', True), ('plan_row__isnull', True), ('school_shelf__isnull', False), ('student_work__isnull', True), ('work__isnull', True)), _connector='OR'), name='attachment_has_exactly_one_owner'),
        ),
    ]
