# Generated by Django 5.1 on 2026-08-22 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0009_school_default_grading_system_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("bug", "об ошибке"), ("idea", "предложение")],
                        default="bug",
                        max_length=8,
                        verbose_name="kind",
                    ),
                ),
                ("text", models.TextField(max_length=4000, verbose_name="text")),
                (
                    "page",
                    models.CharField(blank=True, max_length=200, verbose_name="page"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="handled at"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="schools.school",
                        verbose_name="school",
                    ),
                ),
            ],
            options={
                "verbose_name": "feedback message",
                "verbose_name_plural": "feedback messages",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["handled_at", "-created_at"],
                        name="feedback_me_handled_bf9197_idx",
                    )
                ],
            },
        ),
    ]
